/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export interface ObjectMeta {
  location: string
  lastModified: number
  size: number
  eTag?: string
  version?: string
}

export interface PutResult {
  eTag?: string
  version?: string
}

export interface GetResult {
  bytes: Buffer
  meta: ObjectMeta
}

export interface ListResult {
  objects: Array<ObjectMeta>
  commonPrefixes: Array<string>
}

export interface Range {
  start: number
  end: number
}

export declare class ObjectStore {
  static createInMemory(): ObjectStore
  static createLocal(rootPath: string): ObjectStore
  static parseUrl(url: string, options?: Record<string, string> | undefined | null): ObjectStore
  put(path: string, data: Buffer): Promise<PutResult>
  get(path: string): Promise<Buffer>
  getWithMeta(path: string): Promise<GetResult>
  head(path: string): Promise<ObjectMeta>
  delete(path: string): Promise<void>
  list(prefix?: string | undefined | null): Promise<Array<ObjectMeta>>
  listWithDelimiter(prefix?: string | undefined | null): Promise<ListResult>
  copy(from: string, to: string): Promise<void>
  rename(from: string, to: string): Promise<void>
  getRanges(path: string, ranges: Array<Range>): Promise<Array<Buffer>>
}
