/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare const __napiBindingTarget: "native" | "wasm32-wasi" | "wasm32-wasip1";

export interface ObjectMeta {
  location: string;
  lastModified: number;
  size: number;
  eTag?: string;
  version?: string;
}

export interface PutResult {
  eTag?: string;
  version?: string;
}

export interface GetResult {
  bytes: Buffer;
  meta: ObjectMeta;
}

export interface ListResult {
  objects: Array<ObjectMeta>;
  commonPrefixes: Array<string>;
}

export interface Range {
  start: number;
  end: number;
}

export interface GetRangeInput {
  start?: number;
  end?: number;
  offset?: number;
  suffix?: number;
}

export interface GetOptionsInput {
  ifMatch?: string;
  ifNoneMatch?: string;
  ifModifiedSince?: number;
  ifUnmodifiedSince?: number;
  range?: GetRangeInput;
  version?: string;
  head?: boolean;
}

export interface UpdateVersionInput {
  eTag?: string;
  version?: string;
}

export interface PutOptionsInput {
  modeOverwrite?: boolean;
  modeCreate?: boolean;
  modeUpdate?: UpdateVersionInput;
}

export interface CopyOptionsInput {
  ifNotExists?: boolean;
}

export interface RenameOptionsInput {
  targetModeOverwrite?: boolean;
  targetModeCreate?: boolean;
}

export declare class ObjectStore {
  static createInMemory(): ObjectStore;
  static createLocal(rootPath: string): ObjectStore;
  static parseUrl(url: string, options?: Record<string, string> | undefined | null): ObjectStore;
  copy(from: string, to: string): Promise<void>;
  copyOpts(from: string, to: string, options?: CopyOptionsInput | undefined | null): Promise<void>;
  delete(path: string): Promise<void>;
  get(path: string): Promise<Buffer>;
  getWithMeta(path: string): Promise<GetResult>;
  getOpts(path: string, options: GetOptionsInput): Promise<Buffer>;
  head(path: string): Promise<ObjectMeta>;
  list(prefix?: string | undefined | null): Promise<Array<ObjectMeta>>;
  listWithDelimiter(prefix?: string | undefined | null): Promise<ListResult>;
  put(path: string, data: Buffer): Promise<PutResult>;
  putOpts(path: string, data: Buffer, options: PutOptionsInput): Promise<PutResult>;
  getRanges(path: string, ranges: Array<Range>): Promise<Array<Buffer>>;
  rename(from: string, to: String): Promise<void>;
  renameOpts(
    from: string,
    to: String,
    options?: RenameOptionsInput | undefined | null,
  ): Promise<void>;
}
